package main

import (
	"bookshopV1/handlers"
	"log"

	_ "bookshopV1/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware
)

type RequestBody struct {
	Data string `json:"data"`
}

// @title           Bookshop swagger documentation
// @version         1.0
// @description		API Server for book catalog
// @host      localhost:9000
// @BasePath  /

func main() {

	handlersV1 := handlers.New()

	router := gin.Default()
	router.Use(gin.Logger())

	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	router.GET("/:id", handlersV1.GetBookById)

	router.PUT("/", handlersV1.CreateBook)

	router.DELETE("/", handlersV1.DeleteBook)

	router.POST("/", handlersV1.EditBook)

	router.PUT("/genre/", handlersV1.CreateGenre)

	router.GET("/genre/:limit", handlersV1.GetGenres)

	router.Run(":9000")

}

func CheckError(err error) {
	if err != nil {
		log.Fatal(err)
	}
}
